export const ActionTypes = {
    // HOME
    SET_HOME : "SET_HOME",
    // PLayLIST DETAILS
    SET_PLAYLIST:"SET_PLAYLIST",
    SET_SELECT_SONG:"SET_SELECT_SONG",
    REMOVE_SELECT_SONG:"REMOVE_SELECT_SONG",
    SET_ADD_SONG:"SET_ADD_SONG",
    REMOVE_ADD_SONG:"REMOVE_ADD_SONG",
    // MUSIC PLAYER
    SET_PLAYING_SONG:"SET_PLAYING_SONG",
    SET_PLAYING_PLAYLIST:"SET_PLAYING_PLAYLIST",
    SLICE_PLAYING_PLAYLIST:"SLICE_PLAYING_PLAYLIST",
    NEXT_SONG:"NEXT_SONG",
    PREV_SONG:"PREV_SONG",
    // SEARCH
    SET_SEARCH_RESULT:"SET_SEARCH_RESULT",
    REMOVE_SEARCH_RESULT:"REMOVE_SEARCH_RESULT",
    // EXPLORE
    SET_EXPLORE:"SET_EXPLORE",
    ADD_EXPLORE:"ADD_EXPLORE",
    // SONG PAGE
    SET_SONG:"SET_SONG",
    SET_SONG_LYRIC:"SET_SONG_LYRIC",

    // TOPIC PAGE
    SET_TOPIC:"SET_TOPIC",


    // VIDEO/MV PAGE
    SET_VIDEO:"SET_VIDEO",
}