export const ActionTypes = {
    SET_HOME : "SET_HOME",

    SET_PLAYLIST:"SET_PLAYLIST",
    SET_SELECT_SONG:"SET_SELECT_SONG",
    REMOVE_SELECT_SONG:"REMOVE_SELECT_SONG",
    SET_ADD_SONG:"SET_ADD_SONG",
    REMOVE_ADD_SONG:"REMOVE_ADD_SONG",
    
    SET_PLAYING_SONG:"SET_PLAYING_SONG",
    SET_PLAYING_PLAYLIST:"SET_PLAYING_PLAYLIST",
    SLICE_PLAYING_PLAYLIST:"SLICE_PLAYING_PLAYLIST",
    NEXT_SONG:"NEXT_SONG",
    PREV_SONG:"PREV_SONG",
}